<a href="https://colab.research.google.com/github/Cyber-Dust/DSCI250/blob/main/H3_volk_dasean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dasean Volk, dvolk@usc.edu

Fall 2021, DSCI 250

Homework #3


Homework Notes
Train the network so that is has weights that it calculates. As you train it should get closer and closer to 0. Do not feed it new data.
The code already does the training. Do it with a calculator, do not wirte code. Show him the and, or, xor results. 

Q2: do it for the data we have, feed the 101 into the equation on a hand calculator.

In [ ]:
import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],4) 
        self.weights2   = np.random.rand(4,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * 
                                            sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2


if __name__ == "__main__":
    X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
    y = np.array([[0],[1],[1],[0]])
    nn = NeuralNetwork(X,y)

    for i in range(10000):
        nn.feedforward()
        nn.backprop()


    print(nn.weights1)
    print(nn.weights2)
    print(nn.output)

[[ 2.20159548  3.19227181  7.4402347   2.38699948]
 [-1.72709034  4.07388805  7.0283079   3.41523078]
 [ 2.11380999 -5.6280187  -3.35432516 -4.52686116]]
[[-5.73167376]
 [-7.8338544 ]
 [12.03262855]
 [-6.64875403]]
[[0.00810593]
 [0.9950759 ]
 [0.99220969]
 [0.00633841]]


In [1]:
import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],4) 
        self.weights2   = np.random.rand(4,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * 
                                            sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2


if __name__ == "__main__":
    X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
    y = np.array([[0],[1],[1],[0]])
    nn = NeuralNetwork(X,y)

    for i in range(100):
        nn.feedforward()
        nn.backprop()


    print(nn.weights1)
    print(nn.weights2)
    print(nn.output)

[[0.99607199 0.02738465 1.23051106 0.39596209]
 [1.0167252  0.48993733 1.48950075 0.18381434]
 [0.45965679 0.53444755 0.34685532 0.32440784]]
[[ 0.45988694]
 [-0.69412783]
 [ 0.85790304]
 [-0.84032354]]
[[0.46594052]
 [0.51937062]
 [0.51848599]
 [0.53216301]]


In [2]:
import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],4) 
        self.weights2   = np.random.rand(4,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * 
                                            sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2


if __name__ == "__main__":
    X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
    y = np.array([[0],[1],[1],[0]])
    nn = NeuralNetwork(X,y)

    for i in range(500):
        nn.feedforward()
        nn.backprop()


    print(nn.weights1)
    print(nn.weights2)
    print(nn.output)

[[-1.39910639  5.74470166 -0.75738444  5.42186206]
 [ 5.02693727 -4.02460786 -1.64702647  5.04163119]
 [-0.63907041  1.7230055   1.55966439 -1.48369424]]
[[-5.5916205 ]
 [-6.21553215]
 [ 2.89984744]
 [ 7.81100782]]
[[0.03346085]
 [0.94737574]
 [0.942966  ]
 [0.06519942]]


In [3]:
import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],4) 
        self.weights2   = np.random.rand(4,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * 
                                            sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2


if __name__ == "__main__":
    X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
    y = np.array([[0],[1],[1],[0]])
    nn = NeuralNetwork(X,y)

    for i in range(1000):
        nn.feedforward()
        nn.backprop()


    print(nn.weights1)
    print(nn.weights2)
    print(nn.output)

[[ 3.20144537 -1.23926546  3.78290754  6.275262  ]
 [ 3.55933551  3.24659232 -1.84922749  6.07071399]
 [-5.16862946  0.08001477  0.66366956 -2.33984082]]
[[-7.0798302 ]
 [-3.61687604]
 [-4.09859059]
 [ 9.46034533]]
[[0.02200942]
 [0.97358772]
 [0.97053792]
 [0.03064005]]


In [4]:
import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],4) 
        self.weights2   = np.random.rand(4,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * 
                                            sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2


if __name__ == "__main__":
    X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
    y = np.array([[0],[1],[1],[0]])
    nn = NeuralNetwork(X,y)

    for i in range(5000):
        nn.feedforward()
        nn.backprop()


    print(nn.weights1)
    print(nn.weights2)
    print(nn.output)

[[ 2.71636822  6.66596852 -2.10091574  6.12620313]
 [ 3.1803728  -4.15345929  6.08746039  5.88741158]
 [-4.50483771  1.3309134  -0.56782435 -1.54252027]]
[[-5.33064966]
 [-6.52976033]
 [-6.09888559]
 [12.22158863]]
[[0.00508537]
 [0.9890578 ]
 [0.98800445]
 [0.0127901 ]]


In [5]:
import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],4) 
        self.weights2   = np.random.rand(4,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * 
                                            sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2


if __name__ == "__main__":
    X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
    y = np.array([[0],[1],[1],[0]])
    nn = NeuralNetwork(X,y)

    for i in range(20000):
        nn.feedforward()
        nn.backprop()


    print(nn.weights1)
    print(nn.weights2)
    print(nn.output)

[[ 2.87635397  6.54211105 -4.28271481  7.07986902]
 [ 2.61958122  6.63501171  7.33099491 -2.20404494]
 [-4.20084521 -1.6782659   1.10362437 -0.95080619]]
[[-4.71241442]
 [14.53998336]
 [-8.189897  ]
 [-7.95887559]]
[[0.00212797]
 [0.99406368]
 [0.99434624]
 [0.00651417]]
