<a href="https://colab.research.google.com/github/Cyber-Dust/DSCI250/blob/main/H3_volk_dasean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dasean Volk, dvolk@usc.edu

Fall 2021, DSCI 250

Homework #3


In [1]:
import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],4) 
        self.weights2   = np.random.rand(4,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * 
                                            sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2


if __name__ == "__main__":
    X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
    y = np.array([[0],[1],[1],[0]])
    nn = NeuralNetwork(X,y)

    for i in range(10000):
        nn.feedforward()
        nn.backprop()


    print(nn.weights1)
    print(nn.weights2)
    print(nn.output)

[[ 2.20159548  3.19227181  7.4402347   2.38699948]
 [-1.72709034  4.07388805  7.0283079   3.41523078]
 [ 2.11380999 -5.6280187  -3.35432516 -4.52686116]]
[[-5.73167376]
 [-7.8338544 ]
 [12.03262855]
 [-6.64875403]]
[[0.00810593]
 [0.9950759 ]
 [0.99220969]
 [0.00633841]]
